#' Community survey example dataset
#'
#' A small synthetic survey dataset used throughout the package as a runnable
#' example. It backs the function examples, serves as a teaching dataset for
#' new users, and demonstrates cross-platform save and load behavior. The 100
#' respondents and 15 variables are chosen to exercise the kinds of data
#' social-science users actually have: Likert scales, dichotomies, a
#' multi-category variable, continuous measures, and SPSS-style user-defined
#' missing values. The data are synthetic, but the relationships among the
#' variables are realistic.
#'
#' \code{community} is the clean default example dataset. For a companion
#' dataset that deliberately carries undeclared missing-value codes, stripped
#' value labels, and an imperfect scale -- the material the data-cleaning
#' workflow operates on -- see \code{\link{clinic}}.
#'
#' @format A data frame with 100 rows and 15 variables:
#' \describe{
#'   \item{RespondentID}{Respondent ID, character ("R001", "R002", ...).}
#'   \item{Income}{Annual income (USD). Carries SPSS-style missing values
#'     (-99 Refused, -98 Don't know).}
#'   \item{Education}{Highest education level, 5 categories (1 Some high
#'     school, 2 High school graduate, 3 Some college, 4 Bachelor's degree,
#'     5 Graduate degree). Carries SPSS-style missing values (-99 Refused,
#'     -98 Don't know).}
#'   \item{Age}{Age in years (integer, 18-80).}
#'   \item{WellbeingScore}{Flourishing score (integer, 0-100); built with an
#'     Income-by-Age interaction.}
#'   \item{Volunteer}{Volunteered in past year, dichotomy coded 0/1 (0 No,
#'     1 Yes).}
#'   \item{OwnsHome}{Owns home, dichotomy coded 1/2 (1 Yes, 2 No); recode to
#'     0/1 before use as a logistic-regression outcome.}
#'   \item{Smoker}{Current smoker, dichotomy coded 0/1 (0 No, 1 Yes). Carries
#'     an SPSS-style missing value (-99 Refused).}
#'   \item{CommuteTime}{Daily commute time in minutes (integer); deliberately
#'     near-independent of the other variables.}
#'   \item{Region}{Region of residence, 4 categories (1 North, 2 South,
#'     3 East, 4 West).}
#'   \item{Environment1}{"Climate change is a serious threat." 5-point Likert
#'     (1 Strongly Disagree to 5 Strongly Agree). Carries SPSS-style missing
#'     values (-99 Refused, -98 Don't know).}
#'   \item{Environment2}{"Concern about the environment is exaggerated."
#'     5-point Likert; reverse-keyed (the variable label ends in " R").
#'     Reverse-code before scale scoring.}
#'   \item{Environment3}{"Government should do more for the environment."
#'     5-point Likert. Carries SPSS-style missing values (-99 Refused,
#'     -98 Don't know).}
#'   \item{Environment4}{"I would pay more for environmentally friendly
#'     products." 5-point Likert.}
#'   \item{Environment5}{"Pollution is a major cause of public health
#'     problems." 5-point Likert; weakly loaded (a Cronbach's-alpha drop
#'     candidate when scoring the scale).}
#' }
#'
#' @details
#' The five Environment items form a single attitude scale: item 2 is
#' reverse-keyed, and item 5 is the weak item that scale-reliability output
#' flags for dropping. Income, Education, Smoker, Environment1, and
#' Environment3 carry SPSS-style missing values, with the codes placed on
#' partly non-overlapping cases so that listwise deletion visibly reduces the
#' analysis sample below the per-variable counts. All of community's
#' missing-value codes are properly declared; for a dataset with undeclared
#' codes and other deliberate data-cleaning problems, see \code{\link{clinic}}.
#'
#' @seealso \code{\link{clinic}}, the messy-data companion dataset.
#'
#' @source Synthetic data generated by
#'   \code{data-raw/community_data_generator.R} (random seed 20260605).
#'
#' @keywords datasets
"community"


#' Clinic intervention example dataset
#'
#' A small synthetic mental-health and wellbeing intervention sample, used as
#' the package's messy-data companion to \code{\link{community}}. Where
#' \code{community} is the clean default, \code{clinic} deliberately carries
#' undeclared missing-value codes, a column whose value labels were stripped on
#' import, and an imperfect scale item, so the declare-and-clean workflow has
#' realistic material to work on. The 70 clients and 16 variables echo the
#' teaching structure of \code{community} -- an interaction, a null variable,
#' non-overlapping missingness, a recode dichotomy, a clean logistic outcome, a
#' multi-category variable, and a Likert battery -- in a psychology setting. The
#' data are synthetic, but the relationships among the variables are realistic.
#'
#' @format A data frame with 70 rows and 16 variables:
#' \describe{
#'   \item{ClientID}{Client ID, character ("C001", "C002", ...).}
#'   \item{Stress}{Perceived stress (integer, 0-40). Carries SPSS-style missing
#'     values (-99 Refused, -98 Don't know).}
#'   \item{SocialSupport}{Perceived social support (integer, 0-24); the
#'     buffering partner in the Stress-by-SocialSupport interaction on
#'     Flourishing.}
#'   \item{SleepHours}{Average nightly sleep in hours. Carries SPSS-style
#'     missing values (-99 Refused, -98 Don't know), placed on cases that do
#'     not overlap the Stress codes, so a model using both predictors drops
#'     more cases than either alone.}
#'   \item{Flourishing}{Flourishing score (integer, 0-100); built with a
#'     Stress-by-SocialSupport interaction (the buffering hypothesis).}
#'   \item{ScreenTime}{Daily screen time in hours; deliberately near-independent
#'     of the other variables.}
#'   \item{PriorTherapy}{Received therapy before the study, dichotomy coded 1/2
#'     (1 Yes, 2 No); recode to 0/1 before use as a logistic-regression
#'     outcome.}
#'   \item{SoughtHelp}{Sought professional help during the study, dichotomy
#'     coded 0/1 (0 No, 1 Yes). A clean logistic-regression outcome.}
#'   \item{Medication}{Currently taking medication, dichotomy coded 0/1 (0 No,
#'     1 Yes). Carries an SPSS-style missing value (-99 Refused).}
#'   \item{Condition}{Treatment condition, 4 categories (1 Control, 2 CBT,
#'     3 Mindfulness, 4 Support group); has a modest effect on Flourishing.}
#'   \item{MoodRating}{Mood rating (integer, 1-10). Arrives "dirty": literal
#'     -99 (Refused) and -98 (Don't know) codes are present in the data with NO
#'     missing-value declaration, the state of play after a CSV or Excel import.
#'     The package's jdeclare_udm() demonstration variable: summary statistics
#'     are poisoned until the codes are declared.}
#'   \item{Anxiety1}{"I felt calm and relaxed." 5-point Likert (1 Not at all to
#'     5 Extremely); reverse-keyed (the variable label ends in " R").
#'     Reverse-code before scale scoring.}
#'   \item{Anxiety2}{"I worried about many different things." 5-point Likert.
#'     Arrives with literal -99/-98 codes present in the data and NO
#'     missing-value declaration -- the undeclared contrast to Anxiety4.}
#'   \item{Anxiety3}{"I felt afraid for no clear reason." 5-point Likert; arrives
#'     with its value labels stripped (a plain numeric column, as after a CSV
#'     import that dropped the labels).}
#'   \item{Anxiety4}{"I had trouble controlling my worry." 5-point Likert.
#'     Carries properly declared SPSS-style missing values (-99 Refused,
#'     -98 Don't know) -- the declared contrast to Anxiety2.}
#'   \item{Anxiety5}{"I felt restless or on edge." 5-point Likert; weakly loaded
#'     (a Cronbach's-alpha drop candidate when scoring the scale).}
#' }
#'
#' @details
#' The five Anxiety items form a single scale, with one deliberate problem per
#' item: Anxiety1 is reverse-keyed; Anxiety2 carries literal -99/-98 codes that
#' are not declared as missing; Anxiety3 arrives with its value labels stripped;
#' Anxiety4 carries the same -99/-98 codes but properly declared (the clean
#' contrast to Anxiety2); and Anxiety5 is the weak item that scale-reliability
#' output flags for dropping. Stress and SleepHours carry SPSS-style missing
#' values on non-overlapping cases, so listwise deletion across both reduces the
#' analysis sample below the per-variable counts. MoodRating and Anxiety2 are
#' the two columns whose -99/-98 codes arrive undeclared, awaiting
#' \code{jdeclare_udm()}. The Stress-by-SocialSupport interaction on Flourishing
#' is the buffering hypothesis (higher social support weakens the negative
#' association between stress and flourishing), and treatment Condition has a
#' modest effect on Flourishing.
#'
#' @seealso \code{\link{community}}, the clean default example dataset.
#'
#' @source Synthetic data generated by
#'   \code{data-raw/clinic_data_generator.R} (random seed 20260614).
#'
#' @keywords datasets
"clinic"
